// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eewibkyupuflbwqwtffp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVld2lia3l1cHVmbGJ3cXd0ZmZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjQzNjksImV4cCI6MjA2MDQwMDM2OX0.NlatW69mJP8bGRyJOsUV8ILwnoSwYWDNIj0lwUJecHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);